// Generated by tabtoy
// Version: 2.8.6
// DO NOT EDIT!!
package cfg

import (
	"fmt"
	"encoding/json"
	"io/ioutil"
)

// Defined in table: DataConfig
type DataConfig struct {

	//Equip
	Equip []*EquipDefine

	//Item
	Item []*ItemDefine
}

// Defined in table: Equip
type EquipDefine struct {

	//唯一ID
	ID int32

	//名字
	Name string

	//描述
	Desc string

	//图标
	Icon string

	//装备类型
	EquipType int32

	//品质
	Qua int32

	//装备耐久
	Dura int32

	//需要等级
	NeedLev int32

	//需要性别
	NeedSex int32

	//需要门派
	NeedMartial int32

	//力道
	LiDao int32

	//力道进阶
	LiDaoStage string

	//内劲
	NeiJin int32

	//内劲进阶
	NeiJinStage string

	//根骨
	GenGu int32

	//根骨进阶
	GenGuStage string

	//身法
	ShenFa int32

	//身法进阶
	ShenFaStage string

	//气血
	QiXue int32

	//气血强化基础值
	QiXueIntensity int32

	//真气
	ZhenQi int32

	//真气强化基础值
	ZhenQiIntensity int32

	//外攻
	WaiGong int32

	//外攻强化基础值
	WaiGongIntensity int32

	//外防
	WaiFang int32

	//外防强化基础值
	WaiFangIntensity int32

	//内攻
	NeiGong int32

	//内攻强化基础值
	NeiGongIntensity int32

	//内防
	NeiFang int32

	//内防强化基础值
	NeiFangIntensity int32

	//命中
	MingZhong int32

	//命中强化基础值
	MingZhongIntensity int32

	//闪避
	ShanBi int32

	//闪避强化基础值
	ShanBiIntensity int32

	//暴击
	BaoJi int32

	//暴击强化基础值
	BaoJiIntensity int32

	//抗暴值
	KangBao int32

	//抗暴值强化基础值
	KangBaoIntensity int32

	//隐藏属性值1
	RandAttrValue_1 string

	//隐藏属性值2
	RandAttrValue_2 string

	//隐藏属性值3
	RandAttrValue_3 string

	//隐藏属性值4
	RandAttrValue_4 string

	//隐藏属性值5
	RandAttrValue_5 string
}

// Defined in table: Item
type ItemDefine struct {

	//唯一ID
	ID int32

	//名字
	Name string

	//描述
	Desc string

	//图标
	Icon string

	//品质
	Qua int32

	//物品类型
	Type int32

	//耐久
	Dura int32

	//价格类型
	PriceType int32

	//购买价格
	Price int32

	//出售价格
	SellPrice int32

	//是否能叠加
	IsPack int32

	//最大叠加数量
	MaxPackCount int32

	//是否能销售
	IsCanSell int32

	//是否能使用
	IsCanUse int32

	//奖励ID
	RewardID int32

	//合成ID
	ComposeID int32

	//等级限制
	Lv int32

	//性别限制
	Sex int32

	//门派限制
	School int32

	//武功境界类型
	GestPhase int32

	//武功境界等级
	GestPhaseLv int32
}

// DataConfig 访问接口
type DataConfigTable struct {

	// 表格原始数据
	DataConfig

	// 索引函数表
	indexFuncByName map[string][]func(*DataConfigTable) error

	// 清空函数表
	clearFuncByName map[string][]func(*DataConfigTable) error

	// 加载前回调
	preFuncList []func(*DataConfigTable) error

	// 加载后回调
	postFuncList []func(*DataConfigTable) error

	EquipByID map[int32]*EquipDefine

	ItemByID map[int32]*ItemDefine
}

// 从json文件加载
func (self *DataConfigTable) Load(filename string) error {

	data, err := ioutil.ReadFile(filename)

	if err != nil {
		return err
	}

	var newTab DataConfig

	// 读取
	err = json.Unmarshal(data, &newTab)
	if err != nil {
		return err
	}

	// 所有加载前的回调
	for _, v := range self.preFuncList {
		if err = v(self); err != nil {
			return err
		}
	}

	// 清除前通知
	for _, list := range self.clearFuncByName {
		for _, v := range list {
			if err = v(self); err != nil {
				return err
			}
		}
	}

	// 复制数据
	self.DataConfig = newTab

	// 生成索引
	for _, list := range self.indexFuncByName {
		for _, v := range list {
			if err = v(self); err != nil {
				return err
			}
		}
	}

	// 所有完成时的回调
	for _, v := range self.postFuncList {
		if err = v(self); err != nil {
			return err
		}
	}

	return nil
}

// 注册外部索引入口, 索引回调, 清空回调
func (self *DataConfigTable) RegisterIndexEntry(name string, indexCallback func(*DataConfigTable) error, clearCallback func(*DataConfigTable) error) {

	indexList, _ := self.indexFuncByName[name]
	clearList, _ := self.clearFuncByName[name]

	if indexCallback != nil {
		indexList = append(indexList, indexCallback)
	}

	if clearCallback != nil {
		clearList = append(clearList, clearCallback)
	}

	self.indexFuncByName[name] = indexList
	self.clearFuncByName[name] = clearList
}

// 注册加载前回调
func (self *DataConfigTable) RegisterPreEntry(callback func(*DataConfigTable) error) {

	self.preFuncList = append(self.preFuncList, callback)
}

// 注册所有完成时回调
func (self *DataConfigTable) RegisterPostEntry(callback func(*DataConfigTable) error) {

	self.postFuncList = append(self.postFuncList, callback)
}

// 创建一个DataConfig表读取实例
func NewDataConfigTable() *DataConfigTable {
	return &DataConfigTable{

		indexFuncByName: map[string][]func(*DataConfigTable) error{

			"Equip": {func(tab *DataConfigTable) error {

				// Equip
				for _, def := range tab.Equip {

					if _, ok := tab.EquipByID[def.ID]; ok {
						panic(fmt.Sprintf("duplicate index in EquipByID: %v", def.ID))
					}

					tab.EquipByID[def.ID] = def

				}

				return nil
			}},

			"Item": {func(tab *DataConfigTable) error {

				// Item
				for _, def := range tab.Item {

					if _, ok := tab.ItemByID[def.ID]; ok {
						panic(fmt.Sprintf("duplicate index in ItemByID: %v", def.ID))
					}

					tab.ItemByID[def.ID] = def

				}

				return nil
			}},
		},

		clearFuncByName: map[string][]func(*DataConfigTable) error{

			"Equip": {func(tab *DataConfigTable) error {

				// Equip

				tab.EquipByID = make(map[int32]*EquipDefine)

				return nil
			}},

			"Item": {func(tab *DataConfigTable) error {

				// Item

				tab.ItemByID = make(map[int32]*ItemDefine)

				return nil
			}},
		},

		EquipByID: make(map[int32]*EquipDefine),

		ItemByID: make(map[int32]*ItemDefine),
	}
}
