// Code generated by protoc-gen-go.
// source: s2s.proto
// DO NOT EDIT!

/*
Package sspb is a generated protocol buffer package.

It is generated from these files:
	s2s.proto

It has these top-level messages:
	GS2MSServerInfoMsg
	MS2GSAddPlayerMoneyMsg
	GS2MSAddPlayerMoneyRetMsg
	MS2GSAddItemMsg
	GS2MSAddItemRetMsg
	MS2CSendMailMsg
	MS2GSSendMailRetMsg
	MS2VSAddNoticeMsg
	VS2MSAddNoticeRetMsg
	MS2VSRemoveNoticeMsg
	VS2MSRemoveNoticeRetMsg
	MS2GSBlockPlayerMsg
	MS2GSUnBlockPlayerMsg
*/
package sspb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 后台交互数据标记枚举
type WebNsqTag int32

const (
	WebNsqTag_Nune         WebNsqTag = 0
	WebNsqTag_AddRes       WebNsqTag = 1
	WebNsqTag_AddItem      WebNsqTag = 2
	WebNsqTag_SendMail     WebNsqTag = 4
	WebNsqTag_AddNotice    WebNsqTag = 5
	WebNsqTag_RemoveNotice WebNsqTag = 6
	WebNsqTag_LockPlayer   WebNsqTag = 7
)

var WebNsqTag_name = map[int32]string{
	0: "Nune",
	1: "AddRes",
	2: "AddItem",
	4: "SendMail",
	5: "AddNotice",
	6: "RemoveNotice",
	7: "LockPlayer",
}
var WebNsqTag_value = map[string]int32{
	"Nune":         0,
	"AddRes":       1,
	"AddItem":      2,
	"SendMail":     4,
	"AddNotice":    5,
	"RemoveNotice": 6,
	"LockPlayer":   7,
}

func (x WebNsqTag) String() string {
	return proto.EnumName(WebNsqTag_name, int32(x))
}
func (WebNsqTag) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// 服务器在线情况
type GS2MSServerInfoMsg struct {
	SID       int32 `protobuf:"varint,1,opt,name=SID" json:"SID,omitempty"`
	Name      int32 `protobuf:"varint,2,opt,name=Name" json:"Name,omitempty"`
	OnlineNum int32 `protobuf:"varint,3,opt,name=OnlineNum" json:"OnlineNum,omitempty"`
}

func (m *GS2MSServerInfoMsg) Reset()                    { *m = GS2MSServerInfoMsg{} }
func (m *GS2MSServerInfoMsg) String() string            { return proto.CompactTextString(m) }
func (*GS2MSServerInfoMsg) ProtoMessage()               {}
func (*GS2MSServerInfoMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GS2MSServerInfoMsg) GetSID() int32 {
	if m != nil {
		return m.SID
	}
	return 0
}

func (m *GS2MSServerInfoMsg) GetName() int32 {
	if m != nil {
		return m.Name
	}
	return 0
}

func (m *GS2MSServerInfoMsg) GetOnlineNum() int32 {
	if m != nil {
		return m.OnlineNum
	}
	return 0
}

// 给玩家添加金钱
type MS2GSAddPlayerMoneyMsg struct {
	Token    string `protobuf:"bytes,1,opt,name=Token" json:"Token,omitempty"`
	PlayerID int32  `protobuf:"varint,2,opt,name=PlayerID" json:"PlayerID,omitempty"`
	Currency int32  `protobuf:"varint,3,opt,name=Currency" json:"Currency,omitempty"`
	Value    int32  `protobuf:"varint,4,opt,name=Value" json:"Value,omitempty"`
}

func (m *MS2GSAddPlayerMoneyMsg) Reset()                    { *m = MS2GSAddPlayerMoneyMsg{} }
func (m *MS2GSAddPlayerMoneyMsg) String() string            { return proto.CompactTextString(m) }
func (*MS2GSAddPlayerMoneyMsg) ProtoMessage()               {}
func (*MS2GSAddPlayerMoneyMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *MS2GSAddPlayerMoneyMsg) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *MS2GSAddPlayerMoneyMsg) GetPlayerID() int32 {
	if m != nil {
		return m.PlayerID
	}
	return 0
}

func (m *MS2GSAddPlayerMoneyMsg) GetCurrency() int32 {
	if m != nil {
		return m.Currency
	}
	return 0
}

func (m *MS2GSAddPlayerMoneyMsg) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

// 给玩家添加金钱回馈
type GS2MSAddPlayerMoneyRetMsg struct {
	Token     string `protobuf:"bytes,1,opt,name=Token" json:"Token,omitempty"`
	PlayerID  int32  `protobuf:"varint,2,opt,name=PlayerID" json:"PlayerID,omitempty"`
	Currency  int32  `protobuf:"varint,3,opt,name=Currency" json:"Currency,omitempty"`
	Value     int32  `protobuf:"varint,4,opt,name=Value" json:"Value,omitempty"`
	ErrorCode int32  `protobuf:"varint,5,opt,name=ErrorCode" json:"ErrorCode,omitempty"`
}

func (m *GS2MSAddPlayerMoneyRetMsg) Reset()                    { *m = GS2MSAddPlayerMoneyRetMsg{} }
func (m *GS2MSAddPlayerMoneyRetMsg) String() string            { return proto.CompactTextString(m) }
func (*GS2MSAddPlayerMoneyRetMsg) ProtoMessage()               {}
func (*GS2MSAddPlayerMoneyRetMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GS2MSAddPlayerMoneyRetMsg) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *GS2MSAddPlayerMoneyRetMsg) GetPlayerID() int32 {
	if m != nil {
		return m.PlayerID
	}
	return 0
}

func (m *GS2MSAddPlayerMoneyRetMsg) GetCurrency() int32 {
	if m != nil {
		return m.Currency
	}
	return 0
}

func (m *GS2MSAddPlayerMoneyRetMsg) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *GS2MSAddPlayerMoneyRetMsg) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

// 给玩家添加物品
type MS2GSAddItemMsg struct {
	Token        string `protobuf:"bytes,1,opt,name=Token" json:"Token,omitempty"`
	PlayerID     int32  `protobuf:"varint,2,opt,name=PlayerID" json:"PlayerID,omitempty"`
	ItemCategory int32  `protobuf:"varint,3,opt,name=ItemCategory" json:"ItemCategory,omitempty"`
	ItemTypeID   int32  `protobuf:"varint,4,opt,name=ItemTypeID" json:"ItemTypeID,omitempty"`
	Count        int32  `protobuf:"varint,5,opt,name=Count" json:"Count,omitempty"`
}

func (m *MS2GSAddItemMsg) Reset()                    { *m = MS2GSAddItemMsg{} }
func (m *MS2GSAddItemMsg) String() string            { return proto.CompactTextString(m) }
func (*MS2GSAddItemMsg) ProtoMessage()               {}
func (*MS2GSAddItemMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *MS2GSAddItemMsg) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *MS2GSAddItemMsg) GetPlayerID() int32 {
	if m != nil {
		return m.PlayerID
	}
	return 0
}

func (m *MS2GSAddItemMsg) GetItemCategory() int32 {
	if m != nil {
		return m.ItemCategory
	}
	return 0
}

func (m *MS2GSAddItemMsg) GetItemTypeID() int32 {
	if m != nil {
		return m.ItemTypeID
	}
	return 0
}

func (m *MS2GSAddItemMsg) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

// 给玩家添加物品回馈
type GS2MSAddItemRetMsg struct {
	Token        string `protobuf:"bytes,1,opt,name=Token" json:"Token,omitempty"`
	PlayerID     int32  `protobuf:"varint,2,opt,name=PlayerID" json:"PlayerID,omitempty"`
	ItemCategory int32  `protobuf:"varint,3,opt,name=ItemCategory" json:"ItemCategory,omitempty"`
	ItemTypeID   int32  `protobuf:"varint,4,opt,name=ItemTypeID" json:"ItemTypeID,omitempty"`
	Count        int32  `protobuf:"varint,5,opt,name=Count" json:"Count,omitempty"`
	ErrorCode    int32  `protobuf:"varint,6,opt,name=ErrorCode" json:"ErrorCode,omitempty"`
}

func (m *GS2MSAddItemRetMsg) Reset()                    { *m = GS2MSAddItemRetMsg{} }
func (m *GS2MSAddItemRetMsg) String() string            { return proto.CompactTextString(m) }
func (*GS2MSAddItemRetMsg) ProtoMessage()               {}
func (*GS2MSAddItemRetMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GS2MSAddItemRetMsg) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *GS2MSAddItemRetMsg) GetPlayerID() int32 {
	if m != nil {
		return m.PlayerID
	}
	return 0
}

func (m *GS2MSAddItemRetMsg) GetItemCategory() int32 {
	if m != nil {
		return m.ItemCategory
	}
	return 0
}

func (m *GS2MSAddItemRetMsg) GetItemTypeID() int32 {
	if m != nil {
		return m.ItemTypeID
	}
	return 0
}

func (m *GS2MSAddItemRetMsg) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *GS2MSAddItemRetMsg) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

// 发送邮件
type MS2CSendMailMsg struct {
	Token     string                      `protobuf:"bytes,1,opt,name=Token" json:"Token,omitempty"`
	PlayerID  int32                       `protobuf:"varint,2,opt,name=PlayerID" json:"PlayerID,omitempty"`
	Topic     string                      `protobuf:"bytes,3,opt,name=Topic" json:"Topic,omitempty"`
	Content   string                      `protobuf:"bytes,4,opt,name=Content" json:"Content,omitempty"`
	Diamond   int32                       `protobuf:"varint,5,opt,name=Diamond" json:"Diamond,omitempty"`
	Silver    int32                       `protobuf:"varint,6,opt,name=Silver" json:"Silver,omitempty"`
	ItemList  []*MS2CSendMailMsg_ItemInfo `protobuf:"bytes,7,rep,name=ItemList" json:"ItemList,omitempty"`
	ID        int32                       `protobuf:"varint,8,opt,name=ID" json:"ID,omitempty"`
	SID       int32                       `protobuf:"varint,9,opt,name=SID" json:"SID,omitempty"`
	IsSendAll bool                        `protobuf:"varint,10,opt,name=IsSendAll" json:"IsSendAll,omitempty"`
}

func (m *MS2CSendMailMsg) Reset()                    { *m = MS2CSendMailMsg{} }
func (m *MS2CSendMailMsg) String() string            { return proto.CompactTextString(m) }
func (*MS2CSendMailMsg) ProtoMessage()               {}
func (*MS2CSendMailMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *MS2CSendMailMsg) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *MS2CSendMailMsg) GetPlayerID() int32 {
	if m != nil {
		return m.PlayerID
	}
	return 0
}

func (m *MS2CSendMailMsg) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *MS2CSendMailMsg) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *MS2CSendMailMsg) GetDiamond() int32 {
	if m != nil {
		return m.Diamond
	}
	return 0
}

func (m *MS2CSendMailMsg) GetSilver() int32 {
	if m != nil {
		return m.Silver
	}
	return 0
}

func (m *MS2CSendMailMsg) GetItemList() []*MS2CSendMailMsg_ItemInfo {
	if m != nil {
		return m.ItemList
	}
	return nil
}

func (m *MS2CSendMailMsg) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *MS2CSendMailMsg) GetSID() int32 {
	if m != nil {
		return m.SID
	}
	return 0
}

func (m *MS2CSendMailMsg) GetIsSendAll() bool {
	if m != nil {
		return m.IsSendAll
	}
	return false
}

type MS2CSendMailMsg_ItemInfo struct {
	ItemTypeID   int32 `protobuf:"varint,1,opt,name=ItemTypeID" json:"ItemTypeID,omitempty"`
	Count        int32 `protobuf:"varint,2,opt,name=Count" json:"Count,omitempty"`
	ItemCategory int32 `protobuf:"varint,3,opt,name=ItemCategory" json:"ItemCategory,omitempty"`
}

func (m *MS2CSendMailMsg_ItemInfo) Reset()                    { *m = MS2CSendMailMsg_ItemInfo{} }
func (m *MS2CSendMailMsg_ItemInfo) String() string            { return proto.CompactTextString(m) }
func (*MS2CSendMailMsg_ItemInfo) ProtoMessage()               {}
func (*MS2CSendMailMsg_ItemInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5, 0} }

func (m *MS2CSendMailMsg_ItemInfo) GetItemTypeID() int32 {
	if m != nil {
		return m.ItemTypeID
	}
	return 0
}

func (m *MS2CSendMailMsg_ItemInfo) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *MS2CSendMailMsg_ItemInfo) GetItemCategory() int32 {
	if m != nil {
		return m.ItemCategory
	}
	return 0
}

// 发送邮件回馈
type MS2GSSendMailRetMsg struct {
	Token     string `protobuf:"bytes,1,opt,name=Token" json:"Token,omitempty"`
	ErrorCode int32  `protobuf:"varint,2,opt,name=ErrorCode" json:"ErrorCode,omitempty"`
}

func (m *MS2GSSendMailRetMsg) Reset()                    { *m = MS2GSSendMailRetMsg{} }
func (m *MS2GSSendMailRetMsg) String() string            { return proto.CompactTextString(m) }
func (*MS2GSSendMailRetMsg) ProtoMessage()               {}
func (*MS2GSSendMailRetMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *MS2GSSendMailRetMsg) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *MS2GSSendMailRetMsg) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

// 增加公告
type MS2VSAddNoticeMsg struct {
	Token     string `protobuf:"bytes,1,opt,name=Token" json:"Token,omitempty"`
	Title     string `protobuf:"bytes,2,opt,name=Title" json:"Title,omitempty"`
	Content   string `protobuf:"bytes,3,opt,name=Content" json:"Content,omitempty"`
	StartTime int64  `protobuf:"varint,4,opt,name=StartTime" json:"StartTime,omitempty"`
	EndTime   int64  `protobuf:"varint,5,opt,name=EndTime" json:"EndTime,omitempty"`
	SID       int32  `protobuf:"varint,6,opt,name=SID" json:"SID,omitempty"`
}

func (m *MS2VSAddNoticeMsg) Reset()                    { *m = MS2VSAddNoticeMsg{} }
func (m *MS2VSAddNoticeMsg) String() string            { return proto.CompactTextString(m) }
func (*MS2VSAddNoticeMsg) ProtoMessage()               {}
func (*MS2VSAddNoticeMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *MS2VSAddNoticeMsg) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *MS2VSAddNoticeMsg) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *MS2VSAddNoticeMsg) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *MS2VSAddNoticeMsg) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *MS2VSAddNoticeMsg) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *MS2VSAddNoticeMsg) GetSID() int32 {
	if m != nil {
		return m.SID
	}
	return 0
}

// 增加公告回馈
type VS2MSAddNoticeRetMsg struct {
	Token     string `protobuf:"bytes,1,opt,name=Token" json:"Token,omitempty"`
	ErrorCode int32  `protobuf:"varint,2,opt,name=ErrorCode" json:"ErrorCode,omitempty"`
}

func (m *VS2MSAddNoticeRetMsg) Reset()                    { *m = VS2MSAddNoticeRetMsg{} }
func (m *VS2MSAddNoticeRetMsg) String() string            { return proto.CompactTextString(m) }
func (*VS2MSAddNoticeRetMsg) ProtoMessage()               {}
func (*VS2MSAddNoticeRetMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *VS2MSAddNoticeRetMsg) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *VS2MSAddNoticeRetMsg) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

// 删除公告
type MS2VSRemoveNoticeMsg struct {
	Token string `protobuf:"bytes,1,opt,name=Token" json:"Token,omitempty"`
	ID    int32  `protobuf:"varint,2,opt,name=ID" json:"ID,omitempty"`
}

func (m *MS2VSRemoveNoticeMsg) Reset()                    { *m = MS2VSRemoveNoticeMsg{} }
func (m *MS2VSRemoveNoticeMsg) String() string            { return proto.CompactTextString(m) }
func (*MS2VSRemoveNoticeMsg) ProtoMessage()               {}
func (*MS2VSRemoveNoticeMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *MS2VSRemoveNoticeMsg) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *MS2VSRemoveNoticeMsg) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

// 删除公告回馈
type VS2MSRemoveNoticeRetMsg struct {
	Token     string `protobuf:"bytes,1,opt,name=Token" json:"Token,omitempty"`
	ID        int32  `protobuf:"varint,2,opt,name=ID" json:"ID,omitempty"`
	ErrorCode int32  `protobuf:"varint,3,opt,name=ErrorCode" json:"ErrorCode,omitempty"`
}

func (m *VS2MSRemoveNoticeRetMsg) Reset()                    { *m = VS2MSRemoveNoticeRetMsg{} }
func (m *VS2MSRemoveNoticeRetMsg) String() string            { return proto.CompactTextString(m) }
func (*VS2MSRemoveNoticeRetMsg) ProtoMessage()               {}
func (*VS2MSRemoveNoticeRetMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *VS2MSRemoveNoticeRetMsg) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *VS2MSRemoveNoticeRetMsg) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *VS2MSRemoveNoticeRetMsg) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

// 封号
type MS2GSBlockPlayerMsg struct {
	Token    string `protobuf:"bytes,1,opt,name=Token" json:"Token,omitempty"`
	PlayerID int32  `protobuf:"varint,2,opt,name=PlayerID" json:"PlayerID,omitempty"`
}

func (m *MS2GSBlockPlayerMsg) Reset()                    { *m = MS2GSBlockPlayerMsg{} }
func (m *MS2GSBlockPlayerMsg) String() string            { return proto.CompactTextString(m) }
func (*MS2GSBlockPlayerMsg) ProtoMessage()               {}
func (*MS2GSBlockPlayerMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *MS2GSBlockPlayerMsg) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *MS2GSBlockPlayerMsg) GetPlayerID() int32 {
	if m != nil {
		return m.PlayerID
	}
	return 0
}

// 解除封号
type MS2GSUnBlockPlayerMsg struct {
	Token    string `protobuf:"bytes,1,opt,name=Token" json:"Token,omitempty"`
	PlayerID int32  `protobuf:"varint,2,opt,name=PlayerID" json:"PlayerID,omitempty"`
}

func (m *MS2GSUnBlockPlayerMsg) Reset()                    { *m = MS2GSUnBlockPlayerMsg{} }
func (m *MS2GSUnBlockPlayerMsg) String() string            { return proto.CompactTextString(m) }
func (*MS2GSUnBlockPlayerMsg) ProtoMessage()               {}
func (*MS2GSUnBlockPlayerMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *MS2GSUnBlockPlayerMsg) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *MS2GSUnBlockPlayerMsg) GetPlayerID() int32 {
	if m != nil {
		return m.PlayerID
	}
	return 0
}

func init() {
	proto.RegisterType((*GS2MSServerInfoMsg)(nil), "sspb.GS2MSServerInfoMsg")
	proto.RegisterType((*MS2GSAddPlayerMoneyMsg)(nil), "sspb.MS2GSAddPlayerMoneyMsg")
	proto.RegisterType((*GS2MSAddPlayerMoneyRetMsg)(nil), "sspb.GS2MSAddPlayerMoneyRetMsg")
	proto.RegisterType((*MS2GSAddItemMsg)(nil), "sspb.MS2GSAddItemMsg")
	proto.RegisterType((*GS2MSAddItemRetMsg)(nil), "sspb.GS2MSAddItemRetMsg")
	proto.RegisterType((*MS2CSendMailMsg)(nil), "sspb.MS2CSendMailMsg")
	proto.RegisterType((*MS2CSendMailMsg_ItemInfo)(nil), "sspb.MS2CSendMailMsg.ItemInfo")
	proto.RegisterType((*MS2GSSendMailRetMsg)(nil), "sspb.MS2GSSendMailRetMsg")
	proto.RegisterType((*MS2VSAddNoticeMsg)(nil), "sspb.MS2VSAddNoticeMsg")
	proto.RegisterType((*VS2MSAddNoticeRetMsg)(nil), "sspb.VS2MSAddNoticeRetMsg")
	proto.RegisterType((*MS2VSRemoveNoticeMsg)(nil), "sspb.MS2VSRemoveNoticeMsg")
	proto.RegisterType((*VS2MSRemoveNoticeRetMsg)(nil), "sspb.VS2MSRemoveNoticeRetMsg")
	proto.RegisterType((*MS2GSBlockPlayerMsg)(nil), "sspb.MS2GSBlockPlayerMsg")
	proto.RegisterType((*MS2GSUnBlockPlayerMsg)(nil), "sspb.MS2GSUnBlockPlayerMsg")
	proto.RegisterEnum("sspb.WebNsqTag", WebNsqTag_name, WebNsqTag_value)
}

func init() { proto.RegisterFile("s2s.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 643 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xbc, 0x55, 0x4d, 0x8f, 0x93, 0x50,
	0x14, 0x15, 0x68, 0x29, 0xdc, 0xa9, 0x8a, 0xcf, 0x3a, 0xe2, 0xc4, 0x4c, 0x26, 0xac, 0x26, 0x2e,
	0xba, 0xa8, 0x3b, 0xe3, 0x66, 0x64, 0x26, 0x4d, 0xcd, 0xb4, 0x1a, 0xa8, 0xd5, 0x8d, 0x0b, 0x5a,
	0x9e, 0x0d, 0x19, 0x78, 0xaf, 0x02, 0x9d, 0xa4, 0x89, 0x7b, 0x7f, 0x85, 0x2b, 0xff, 0x87, 0xbf,
	0xcd, 0xf7, 0x01, 0xb4, 0x90, 0xcc, 0x68, 0x3a, 0xd1, 0x1d, 0xf7, 0x3e, 0xde, 0xb9, 0xe7, 0x9e,
	0x73, 0x2f, 0x80, 0x99, 0x0d, 0xb2, 0xfe, 0x2a, 0xa5, 0x39, 0x45, 0xad, 0x2c, 0x5b, 0xcd, 0x9d,
	0x4f, 0x80, 0x86, 0xfe, 0x60, 0xec, 0xfb, 0x38, 0xbd, 0xc6, 0xe9, 0x88, 0x7c, 0xa1, 0xe3, 0x6c,
	0x89, 0x2c, 0xd0, 0xfc, 0xd1, 0xb9, 0xad, 0x9c, 0x28, 0xa7, 0x6d, 0x8f, 0x3f, 0x22, 0x04, 0xad,
	0x49, 0x90, 0x60, 0x5b, 0x15, 0x29, 0xf1, 0x8c, 0x9e, 0x83, 0xf9, 0x8e, 0xc4, 0x11, 0xc1, 0x93,
	0x75, 0x62, 0x6b, 0xe2, 0x60, 0x9b, 0x70, 0xbe, 0xc1, 0xe1, 0xd8, 0x1f, 0x0c, 0xfd, 0xb3, 0x30,
	0x7c, 0x1f, 0x07, 0x1b, 0x9c, 0x8e, 0x29, 0xc1, 0x1b, 0x8e, 0xde, 0x83, 0xf6, 0x94, 0x5e, 0x61,
	0x22, 0xf0, 0x4d, 0x4f, 0x06, 0xe8, 0x08, 0x0c, 0xf9, 0x1e, 0x2b, 0x2c, 0xab, 0x54, 0x31, 0x3f,
	0x73, 0xd7, 0x69, 0x8a, 0xc9, 0x62, 0x53, 0x14, 0xaa, 0x62, 0x8e, 0x36, 0x0b, 0xe2, 0x35, 0xb6,
	0x5b, 0xe2, 0x40, 0x06, 0xce, 0x0f, 0x05, 0x9e, 0x89, 0xc6, 0xea, 0xe5, 0x3d, 0x9c, 0xff, 0x27,
	0x06, 0x5c, 0x9d, 0x8b, 0x34, 0xa5, 0xa9, 0x4b, 0x43, 0x6c, 0xb7, 0xa5, 0x3a, 0x55, 0x82, 0xf3,
	0x7b, 0x58, 0xca, 0x33, 0xca, 0x71, 0xb2, 0x1f, 0x2b, 0x07, 0xba, 0xfc, 0xb2, 0x1b, 0xe4, 0x78,
	0x49, 0xd3, 0x92, 0x59, 0x2d, 0x87, 0x8e, 0x01, 0x78, 0x3c, 0xdd, 0xac, 0x30, 0x43, 0x90, 0x14,
	0x77, 0x32, 0xbc, 0xaa, 0x4b, 0xd7, 0x24, 0x2f, 0x38, 0xca, 0xc0, 0xf9, 0xa5, 0x14, 0x83, 0x51,
	0xf0, 0xdb, 0x5b, 0xb8, 0x7f, 0x46, 0xb1, 0x2e, 0xb0, 0xde, 0x14, 0xf8, 0xbb, 0x26, 0x04, 0x76,
	0x7d, 0x4c, 0xc2, 0x71, 0x10, 0xc5, 0xfb, 0xb1, 0x17, 0x37, 0x56, 0xd1, 0x42, 0xd0, 0x16, 0x37,
	0x58, 0x80, 0x6c, 0xe8, 0xb8, 0x94, 0xe4, 0x98, 0x31, 0x6a, 0x89, 0x7c, 0x19, 0xf2, 0x93, 0xf3,
	0x28, 0x48, 0x28, 0x09, 0x0b, 0xae, 0x65, 0x88, 0x0e, 0x41, 0xf7, 0xa3, 0x98, 0xed, 0x58, 0x41,
	0xb5, 0x88, 0xd0, 0x2b, 0x30, 0x78, 0xa7, 0x97, 0x51, 0x96, 0xdb, 0x9d, 0x13, 0xed, 0xf4, 0x60,
	0x70, 0xdc, 0xe7, 0x9b, 0xd9, 0x6f, 0x90, 0xef, 0xf3, 0xb7, 0xf8, 0x7e, 0x7a, 0xd5, 0xfb, 0xe8,
	0x01, 0xa8, 0x8c, 0xb3, 0x21, 0xf0, 0xd8, 0x53, 0xb9, 0xb6, 0xe6, 0x76, 0x6d, 0x99, 0x46, 0xa3,
	0x8c, 0xa3, 0x9c, 0xc5, 0xb1, 0x0d, 0x2c, 0x6f, 0x78, 0xdb, 0xc4, 0x51, 0x28, 0x6b, 0x73, 0xd4,
	0x86, 0x07, 0xca, 0xcd, 0x1e, 0xa8, 0xbb, 0x1e, 0xfc, 0x85, 0xbb, 0xce, 0x08, 0x1e, 0x8b, 0x49,
	0x2f, 0x9b, 0xb9, 0x75, 0x94, 0x6a, 0xa6, 0xaa, 0x4d, 0x53, 0x7f, 0x2a, 0xf0, 0x88, 0x61, 0xcd,
	0xf8, 0x54, 0x4e, 0x68, 0x1e, 0x2d, 0xf0, 0xcd, 0x48, 0x3c, 0x1b, 0xe5, 0xb1, 0x44, 0xe1, 0x59,
	0x1e, 0xec, 0x5a, 0xa7, 0xd5, 0xad, 0x63, 0x95, 0xfd, 0x3c, 0x48, 0xf3, 0x69, 0x94, 0xc8, 0x4d,
	0xd6, 0xbc, 0x6d, 0x82, 0xdf, 0xbb, 0x20, 0xa1, 0x38, 0x6b, 0x8b, 0xb3, 0x32, 0x2c, 0x45, 0xd7,
	0x2b, 0xd1, 0x9d, 0xb7, 0xd0, 0x9b, 0x15, 0xab, 0x23, 0x49, 0xde, 0xa1, 0xe3, 0xd7, 0xd0, 0x13,
	0x0d, 0x7b, 0x38, 0xa1, 0xd7, 0xf8, 0x4f, 0x3d, 0xcb, 0x81, 0x50, 0xcb, 0x81, 0x70, 0x3e, 0xc3,
	0x53, 0xc1, 0x64, 0xf7, 0xf6, 0xad, 0x64, 0x1a, 0x00, 0x75, 0x72, 0x5a, 0x93, 0xdc, 0xb0, 0x70,
	0xf6, 0x4d, 0x4c, 0x17, 0x57, 0xc5, 0x57, 0x76, 0x9f, 0x35, 0x63, 0x23, 0xf2, 0x44, 0x00, 0x7d,
	0x20, 0x77, 0x85, 0x7a, 0x91, 0x80, 0xf9, 0x11, 0xcf, 0x27, 0xd9, 0xd7, 0x69, 0xb0, 0x44, 0x06,
	0xfb, 0x6b, 0xad, 0x09, 0xb6, 0xee, 0x21, 0x00, 0x9d, 0xd9, 0xe1, 0xe1, 0xcc, 0x52, 0xd0, 0x01,
	0x74, 0x8a, 0xaf, 0x9a, 0xa5, 0xa2, 0x2e, 0x18, 0xe5, 0x60, 0x5a, 0x2d, 0x74, 0x1f, 0xcc, 0xca,
	0x35, 0xab, 0xcd, 0xbc, 0xed, 0xee, 0x4a, 0x67, 0xe9, 0x4c, 0x20, 0xb8, 0xac, 0x18, 0x5a, 0x9d,
	0xb9, 0x2e, 0x7e, 0xa6, 0x2f, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0xa6, 0x4d, 0x14, 0x9b, 0x59,
	0x07, 0x00, 0x00,
}
